execute pathogen#infect()

syntax on
filetype plugin indent on

set relativenumber
set ruler
set backspace=indent,eol,start 
set laststatus=2
set clipboard+=unnamed
set pastetoggle=<F3>

let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
